---
- name: Install required softwares
  hosts: all
  tasks:
    - name: install s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: openjdk-8-jdk,b: present,c: yes}
        - {a: git,b: present,c: no}
        - {a: maven,b: present,c: no}
        - {a: tomcat9,b: present,c: no}
        - {a: tomcat9-admin,b: present,c: no}
- name: Continuous download and continuous build
  hosts: devserver
  tasks:
    - name: Download and continuous build
      git:
        repo: https://github.com/intelliqittrainings/maven.git
        dest: dev-git
    - name: create artifacts from the code
      shell: cd dev-git;mvn package
    - name:
      fetch: 
        src: dev-git/webapp/target/webapp.war
        dest: /tmp
- name: continuous Deployment and continuous Testing
  hosts: qaserver
  tasks:
    - name: deploy artifacts into tomcat on qa server
      copy:
        src: /tmp/172.31.2.248/dev-git/webapp/target/webapp.war
        dest: /var/lib/tomcat9/webapps/testapp.war
    - name: Download code
      git: 
       repo: https://github.com/intelliqittrainings/FunctionalTesting.git
       dest: test-get
    - name: Execute the selenium scripts
      shell: java -jar test-git/testing.jar
- name: Continuous Delivery
  hosts: prodserver
  tasks:
    - name: Deploy artifact into tomcat on the prodservers
      copy:
        src: /tmp/54.215.128.136/dev-git/webapp/target/webapp.war
        dest: /var/lib/tomcat9/webapps/prodapp.war  
...

