---
- name: Implementing tags
  hosts: all
  gather_facts: false
  tasks:
    - name: Install tree
      apt:
        name: tree
        state: present
      tags: tree_installation
    - name: create user
      user:
        name: srinathk2
        password: sri
      tags: user_creation
    - name:
      copy:
        src: /etc/passwd
        dest: /tmp
...
