---
- name: Install Jenkins
  hosts: jenkins
  tasks:
    - name: install tomcat9 and tomcat9-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: openjdk-8-jdk,b: present,c: yes}
        - {a: git,b: present,c: no}
        - {a: maven,b: present,c: no}
    - name:
      get_url:
        url: https://get.jenkins.io/war-stable/2.346.2/jenkins.war
        dest: /home/ubuntu
...
