---
- name: Configuring apache2
  hosts: webserver
  tasks:
   - name: Install apache2
     apt:
      name: apache2
      state: present
      update_cache: yes
   - name: Edit the index.html file
     copy:
      content: "srinath"
      dest: /var/www/html/index.html
   - name: Restart apache2
     service:
      name: apache2
      state: restarted
   - name: Check the url response of apache2 on server1
     uri:
      url: http://172.31.6.111
      status_code: 200
   - name: Check the url response of apache2 on server2
     uri:
      url: http://172.31.2.200
      status_code: 200
   - name: Check the url response of apache2 on server2
     uri:
      url: http://172.31.2.118
      status_code: 200
   - name: Check the url response of apache2 on server2
     uri:
      url: http://172.31.1.107
      status_code: 200

...
