---
- name: create mutiple user and copy files
  hosts: all
  tasks:
    - name: create users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: srinath1,b: sri,c: /home/srinath1}
        - {a: raju,b: sri,c: /tmp/raju}
    - name: copy files into users
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/srinath1}
        - {a: /etc/group,b: /tmp/raju}
...
